#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'


# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
# npm run check-lint ||
# (
#         echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
#                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
#         false; 
# )

npm run check-types ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                Typescript Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)



npm run build ||
(
        echo '🚧🏗️👷 Get that weak s**t out of here! 🚧🏗️👷 
                Build Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... 🤔🤔🤔🤔'

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'

